### ISSUE TITLE
プラグインのインストールができない

### ISSUE THREAD

**Issue by nobuhiko** [nanasess/ec-cube-extended#38]
PHP 7.0.15 で確認

**Comment by nanasess** [comment]
#36 の影響でしょうか?

**Comment by nobuhiko** [comment]
単純にSmarty3が原因っぽいです
https://github.com/nanasess/ec-cube-extended/blob/improve/php7/data/Smarty/templates/admin/ownersstore/plugin.tpl#L132

```<!--{ $key }-->``` ってかくと変数としてみなされない

**Comment by nanasess** [comment]
ありがとうございます。マージしておきますね。
