### ISSUE TITLE
Smartyプラグインのエラー

### ISSUE THREAD

**Issue by yuh4** [nanasess/ec-cube-extended#43]
Smartyのプラグイン内で

    require_once $smarty->_get_plugin_filepath('shared', 'escape_special_chars');

このように記載されている箇所で、_get_plugin_filepathのメソッドが無い事が原因でエラーが発生します。
該当箇所は管理画面＞商品並び替えで商品表示時。

	require_once DATA_REALDIR.'smarty_extends/shared.escape_special_chars.php';

このように変更で解決しますが、スマートじゃないのでどうしましょう。。

**Comment by nanasess** [comment]
> `require_once DATA_REALDIR.'smarty_extends/shared.escape_special_chars.php';`

で、いいと思います。 `DATA_REALDIR` は `__DIR__` に置き換えた方がいいかもしれませんね

**Comment by nobuhiko** [comment]
これのはなしですよね？
https://github.com/EC-CUBE/eccube-2_13/pull/128/commits/68b68153025784620dcb6f1c73b5a831040912c2

**Comment by nanasess** [comment]
@nobuhiko それですそれです。 どこかで見たような気がしてたんですけど、確認不足でした 🤕

**Comment by yuh4** [comment]
すいません、確認不足でした 。
